@startuml
!include style.puml
skinparam ArrowFontStyle plain
hide footbox


box Logic LOGIC_COLOR_T1
participant "a:AssignCommand" as AssignCommand LOGIC_COLOR
end box

participant "<<class>>\nClusterUtil" as ClusterUtil #EE82EE

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

group sd assign drivers to all subscribers
    AssignCommand -> ClusterUtil : groupIntoClusters(...)
    activate ClusterUtil

    ClusterUtil -> AssignCommand : clusters of subscribers
    deactivate ClusterUtil

    loop for each cluster
        loop for each subscriber in cluster
            AssignCommand -> Model : setPerson(...)
            activate Model

            Model --> AssignCommand
            deactivate Model
        end
    end
end

@enduml
