@startuml
!include style.puml
skinparam ArrowFontStyle plain
hide footbox


box Logic LOGIC_COLOR_T1
participant "a:AssignCommand" as AssignCommand LOGIC_COLOR
end box

participant "<<class>>\nClusterAssigner" as ClusterAssigner #EE82EE

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

group sd assign drivers to all subscribers
    AssignCommand -> ClusterAssigner : groupIntoClusters(...)
    activate ClusterAssigner

    ClusterAssigner --> AssignCommand : clusters of subscribers
    deactivate ClusterAssigner

    loop for each subscriber in each cluster
        AssignCommand -> Model : setPerson(...)
        activate Model

        Model --> AssignCommand
        deactivate Model
    end
end

@enduml
